# Generated by Django 4.1 on 2023-12-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='userMail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
